[package]
name = "ethashcache"
version = "0.1.0"
authors = []

[lib]
name = "ethashcache"
path = "src/lib.rs"
crate-type = ["dylib"]

[dependencies]
tiny-keccak = "1.3"
rustler = "0.15.1"
rustler_codegen = "0.15.1"
lazy_static = "0.2"
